// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    ext {
        kotlin_version = '2.2.0'
    }

    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.google.com' }

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.15'
    }
}

plugins {
    id 'com.android.application' version '8.7.3' apply false
    id 'com.android.library' version '8.7.3' apply false
    id 'org.jetbrains.kotlin.android' version '1.8.20' apply false
    id 'com.google.gms.google-services' version '4.3.15' apply false
    id("com.google.firebase.crashlytics") version "2.9.9" apply false
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url 'https://maven.accuauth.com/repository/maven-releases/'
            // If your gradle version is greater than 7.0, you need to add the following configuration to allow pulling aar via http
            allowInsecureProtocol = true
        }
    }
}