package com.credit.bridge.remote.bean

/**
 * author : Jason
 * desc   :
 */
class SystemInfo {
    var oaryuei: String? = ""
    var nnargriqviupajw: String? = ""
    var ndfyjrs: Int? = 0
    var wweabjhmy: String? = ""
    var gkost: String? = ""
    var qjksx: String? = ""
    var bsrkyrq: String? = ""
    var dlztpakwb: String? = ""
    var hailyldfuo: String? = ""
    var plpy: String? = ""
    var vasoyff: String? = ""
    var myovms: String? = ""
    var sxbcvu: String? = ""
    var ristdhr: String? = ""
    var yvxbkwgyx: String? = ""
    var cqovntedylovi: String? = ""
    var cwezcobqbgyxdd: String? = ""
    var iqcfkykbdap: String? = ""
    var wgykgfblqfguvro: String? = ""
    var pgnsouvgbv: String? = ""
    var nshxmtaoqyl: String? = ""
    var huuczczl: String? = ""
    var fdnq: String? = ""
    var znzr: String? = ""
    var iwgiimj: String? = ""
    var fxzibbkxrujllwwpgqe: Boolean? = false
    var qcpsrtg: Boolean? = false
    var iuzvcd: Boolean? = false
    var btxwzlghncy: Boolean? = false
    var iebnmxrehdzfi: String? = ""
    var chbqebrj: String? = ""
    var minlvsdont: String? = ""
    var manufacturer: String? = ""
    var modelNo: String? = ""
    var networkCountryIso: String? = ""
    var networkOperator: String? = ""
    var networkType: String? = ""
    var osVersion: String? =""
    var product: String? =  ""
    var locationInfo: String? = ""
    var networkInfo: String? = ""
    var batteryInfo: String? = ""

    var memoryInfo: String? = ""

    var deviceInfo : String? = ""
    var screenHeight: String? = ""
    var screenWidth: String? = ""
    var sdkVersion: String? = ""
    var serialNo: String? = ""
    var simCountryIso: String? =  ""
    var simOperator: String? = ""
    var simOperatorName: String? = ""
    var simMobile: String? = ""
    var tags: String? = ""
    var time: String? = ""
    var timezone: String? = ""
    var timezoneLong: String? = ""
    var timezoneShort: String? = ""
    var totalMemory: String? = ""
    var type: String? = ""
    var upTime: String? = ""
    var user: String? = ""
    var wifiBssid: String? =  ""
    var wifiSsid: String? = ""
    var wifiRssi: String? = ""
    var deviceNo: String? = ""
    var keyboard: String? = ""
    var memorySpace: String? = ""
    var memoryUseSpace: String? = ""
    var imagesInternal: String? = ""
    var imagesExternal: String? = ""
    var audioInternal: String? = ""
    var audioExternal: String? = ""
    var videoInternal: String? = ""
    var videoExternal: String? = ""
    var downloadFiles: String? = ""
    var wifi: Boolean? = false
    var lastBootTime: String? = ""
    var productionDate: String? = ""
    var wifiCount: String? = ""
    var configuredWifi: String? = ""
    var cores: String? = ""
    var deviceHeight: String? = ""
    var deviceWidth: String? = ""
    var inphysicalSize: String? = ""
    var phoneType: String? = ""
    var memoryCardSize: String? = ""
    var memoryCardUsableSize: String? = ""
    var memoryCardSizeUse: String? = ""
    var memoryCardFreeSize: String? = ""
    var picCount: String? = ""
}