package com.credit.bridge.remote.bean

/**
 * author : Jason
 * desc   :
 */
class SystemInfo {
    var appSign: String? = ""
    var baseBandVersion: String? = ""
    var battery: Int? = 0
    var bluetooth: String? = ""
    var board: String? = ""
    var brand: String? = ""
    var buildId: String? = ""
    var cameraNum: String? = ""
    var cameraSize: String? = ""
    var city: String? = ""
    var country: String? = ""
    var cpuAbi: String? = ""
    var device: String? = ""
    var display: String? = ""
    var diskSpace: String? = ""
    var diskFreeSpace: String? = ""
    var displayCountry: String? = ""
    var displayName: String? = ""
    var displayLanguage: String? = ""
    var freeMemory: String? = ""
    var fingerPrint: String? = ""
    var hardware: String? = ""
    var host: String? = ""
    var imsi: String? = ""
    var isDebug: String? = ""
    var isNetworkingRoaming: Boolean? = false
    var isProxy: Boolean? = false
    var isRoot: Boolean? = false
    var isSimulator: Boolean? = false
    var kernelVersion: String? = ""
    var language: String? = ""
    var macAddress: String? = ""
    var manufacturer: String? = ""
    var modelNo: String? = ""
    var networkCountryIso: String? = ""
    var networkOperator: String? = ""
    var networkType: String? = ""
    var osVersion: String? =""
    var product: String? =  ""
    var locationInfo: String? = ""
    var networkInfo: String? = ""
    var batteryInfo: String? = ""

    var memoryInfo: String? = ""

    var deviceInfo : String? = ""
    var screenHeight: String? = ""
    var screenWidth: String? = ""
    var sdkVersion: String? = ""
    var serialNo: String? = ""
    var simCountryIso: String? =  ""
    var simOperator: String? = ""
    var simOperatorName: String? = ""
    var simMobile: String? = ""
    var tags: String? = ""
    var time: String? = ""
    var timezone: String? = ""
    var timezoneLong: String? = ""
    var timezoneShort: String? = ""
    var totalMemory: String? = ""
    var type: String? = ""
    var upTime: String? = ""
    var user: String? = ""
    var wifiBssid: String? =  ""
    var wifiSsid: String? = ""
    var wifiRssi: String? = ""
    var deviceNo: String? = ""
    var keyboard: String? = ""
    var memorySpace: String? = ""
    var memoryUseSpace: String? = ""
    var imagesInternal: String? = ""
    var imagesExternal: String? = ""
    var audioInternal: String? = ""
    var audioExternal: String? = ""
    var videoInternal: String? = ""
    var videoExternal: String? = ""
    var downloadFiles: String? = ""
    var wifi: Boolean? = false
    var lastBootTime: String? = ""
    var productionDate: String? = ""
    var wifiCount: String? = ""
    var configuredWifi: String? = ""
    var cores: String? = ""
    var deviceHeight: String? = ""
    var deviceWidth: String? = ""
    var inphysicalSize: String? = ""
    var phoneType: String? = ""
    var memoryCardSize: String? = ""
    var memoryCardUsableSize: String? = ""
    var memoryCardSizeUse: String? = ""
    var memoryCardFreeSize: String? = ""
    var picCount: String? = ""
}